find_path(POCO_INCLUDE_DIR Poco/Poco.h PATHS /usr/local/include)
find_library(POCO_FOUNDATION PocoFoundation PATHS /usr/local/lib)
find_library(POCO_NET_LIBRARY PocoNet PATHS /usr/local/lib)
find_library(POCO_UTIL_LIBRARY PocoUtil PATHS /usr/local/lib)
find_library(POCO_XML_LIBRARY PocoXML PATHS /usr/local/lib)
find_library(POCO_JSON_LIBRARY PocoJSON PATHS /usr/local/lib)

if (POCO_INCLUDE_DIR AND POCO_FOUNDATION AND POCO_NET_LIBRARY)
   SET (POCO_FOUND TRUE)
   MESSAGE ("POCO found.")
else (POCO_INCLUDE_DIR AND POCO_FOUNDATION AND POCO_NET_LIBRARY)
   SET (POCO_FOUND FALSE)
   MESSAGE ("POCO not found...")
endif (POCO_INCLUDE_DIR AND POCO_FOUNDATION AND POCO_NET_LIBRARY)
